In [51]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sketch

In [52]:
raw_train_data = pd.read_csv('kaggle/input/spaceship-titanic/train.csv')
raw_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [53]:
from sklearn.preprocessing import LabelEncoder

def encode_categorical_data(df):
    label_encoders = {}

    for column in ["PassengerId", "HomePlanet", "CryoSleep", "Cabin", "Destination", "VIP", "Name"]:
        le = LabelEncoder()
        df[column] = le.fit_transform(df[column])
        label_encoders[column] = le

In [54]:
encode_categorical_data(raw_train_data)
raw_train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   int64
 1   HomePlanet    8693 non-null   int64
 2   CryoSleep     8693 non-null   int64
 3   Cabin         8693 non-null   int64
 4   Destination   8693 non-null   int64
 5   Age           8514 non-null   float64
 6   VIP           8693 non-null   int64
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8693 non-null   int64
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), int64(7)
memory usage: 891.5 KB

In [55]:
raw_train_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0,1,0,149,2,39.0,0,0.0,0.0,0.0,0.0,0.0,5252,False
1,1,0,0,2184,2,24.0,0,109.0,9.0,25.0,549.0,44.0,4502,True
2,2,1,0,1,2,58.0,1,43.0,3576.0,0.0,6715.0,49.0,457,False
3,3,1,0,1,2,33.0,0,0.0,1283.0,371.0,3329.0,193.0,7149,False
4,4,0,0,2186,2,16.0,0,303.0,70.0,151.0,565.0,2.0,8319,True

In [56]:
raw_train_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0,1,0,149,2,39.0,0,0.0,0.0,0.0,0.0,0.0,5252,False
1,1,0,0,2184,2,24.0,0,109.0,9.0,25.0,549.0,44.0,4502,True
2,2,1,0,1,2,58.0,1,43.0,3576.0,0.0,6715.0,49.0,457,False
3,3,1,0,1,2,33.0,0,0.0,1283.0,371.0,3329.0,193.0,7149,False
4,4,0,0,2186,2,16.0,0,303.0,70.0,151.0,565.0,2.0,8319,True

In [57]:
missing_props = raw_train_data.isna().mean(axis=0)

In [58]:
raw_train_data.sketch.ask("What is the total count of people who were and were not transported")

In [59]:
raw_train_data.sketch.ask("What is the average age of the passengers")

In [60]:
raw_train_data.sketch.ask("what is the average value of FoodCourt")

In [61]:
raw_test_data = pd.read_csv('kaggle/input/spaceship-titanic/test.csv')
raw_test_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez

In [62]:
encode_categorical_data(raw_test_data)
raw_test_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0,0,1,2784,2,27.0,0,0.0,0.0,0.0,0.0,0.0,2912
1,1,0,0,1867,2,19.0,0,0.0,9.0,0.0,2823.0,0.0,2406
2,2,1,1,257,0,31.0,0,0.0,0.0,0.0,0.0,0.0,3376
3,3,1,0,259,2,38.0,0,0.0,6652.0,0.0,181.0,585.0,2711
4,4,0,0,1940,2,20.0,0,10.0,0.0,635.0,0.0,0.0,668

In [63]:
X, y = raw_train_data.drop('Transported', axis=1), raw_train_data[['Transported']]

In [64]:
X.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0,1,0,149,2,39.0,0,0.0,0.0,0.0,0.0,0.0,5252
1,1,0,0,2184,2,24.0,0,109.0,9.0,25.0,549.0,44.0,4502
2,2,1,0,1,2,58.0,1,43.0,3576.0,0.0,6715.0,49.0,457
3,3,1,0,1,2,33.0,0,0.0,1283.0,371.0,3329.0,193.0,7149
4,4,0,0,2186,2,16.0,0,303.0,70.0,151.0,565.0,2.0,8319

In [65]:
y.head()

   Transported
0        False
1         True
2        False
3        False
4         True

In [66]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1121218)

In [67]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6519 entries, 4724 to 6883
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   6519 non-null   int64
 1   HomePlanet    6519 non-null   int64
 2   CryoSleep     6519 non-null   int64
 3   Cabin         6519 non-null   int64
 4   Destination   6519 non-null   int64
 5   Age           6387 non-null   float64
 6   VIP           6519 non-null   int64
 7   RoomService   6394 non-null   float64
 8   FoodCourt     6379 non-null   float64
 9   ShoppingMall  6365 non-null   float64
 10  Spa           6385 non-null   float64
 11  VRDeck        6381 non-null   float64
 12  Name          6519 non-null   int64
dtypes: float64(6), int64(7)
memory usage: 713.0 KB

In [68]:
import xgboost as xgb

xgb_cl = xgb.XGBClassifier()
print(type(xgb_cl))

<class 'xgboost.sklearn.XGBClassifier'>

In [69]:
from sklearn.metrics import accuracy_score

xgb_cl.fit(X_train, y_train)
preds = xgb_cl.predict(X_test)
adjusted_preds = preds.astype(bool)
accuracy_score(y_test, preds)

0.7874885004599816

# Attempt to tune the parameters for better results using gridsearch

In [70]:
param_grid = {
    "max_depth": [9, 15, 20],
    "learning_rate": [0.1, 0.01, 0.05],
    "gamma": [0, 0.25, 1],
    "reg_lambda": [0, 1, 10],
    "scale_pos_weight": [1, 3, 5],
    "subsample": [0.8],
    "colsample_bytree": [0.5],
}

In [71]:
from sklearn.model_selection import GridSearchCV

# Init classifier
xgb_cl = xgb.XGBClassifier(objective="binary:logistic", )

# Init Grid Search
grid_cv = GridSearchCV(xgb_cl, param_grid, n_jobs=-1, cv=3, scoring="roc_auc", verbose=1)

# Fit
_ = grid_cv.fit(X_train, y_train)

grid_cv.best_score_

Fitting 3 folds for each of 243 candidates, totalling 729 fits

In [ ]:
grid_cv.best_params_

In [ ]:
final_cl = xgb.XGBClassifier(
    **grid_cv.best_params_,
    objective="binary:logistic",
)

_ = final_cl.fit(X_train, y_train)
preds = final_cl.predict(X_test)
adjusted_preds = preds.astype(bool)
accuracy_score(y_test, preds)

# Using the optimized XGBClassifier, run the test set for predictions

In [ ]:
preds = final_cl.predict(raw_test_data)
adjusted_preds = preds.astyle(bool)

final_results = pd.DataFrame()
final_results['PassengerId'] = raw_test_data['PassengerId']
final_results['Transported'] = adjusted_preds

final_results.to_csv("submissions.csv")

final_results.head()